apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
  - namespace.yaml
patchesStrategicMerge:
  - deployment-patch.yaml
configMapGenerator:
  - name: app-config
    envs:
      - configmap.env
secretGenerator:
  - name: app-secret
    envs:
      - secret.env