apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-prod-deployment
spec:
  replicas: 5  # Higher scale replicas for prod environment
  selector:
    matchLabels:
      app: nginx  # This ensures the Deployment manages pods with this label
  template:
    metadata:
      labels:
        app: nginx  # Labels that pods should have
    spec:
      containers:
        - name: nginx
          resources:
            requests:
              cpu: "250m"
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"